# Run unit tests
name: CI

# Triggers the workflow on all push or pull request events
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up JDK 9
        uses: actions/setup-java@v2
        with:
          java-version: '9.0.0+181'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      # Run unit tests
      - name: Run tests with gradle
        run: ./gradlew check --info

      # Upload code coverage data to CodeCov
      - name: Upload CodeCov results
        uses: codecov/codecov-action@v1
